server:
  port: 8080
  servlet:
    session:
      timeout: 360000s
    # 인코딩 UTF-8로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: crimecapturetv
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cctv?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cctv
    password: cctv
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #ddl-auto 뭐가 호완이 안되서 설정한거
  # file upload
  servlet:
    multipart:
      # 파일 업로드 가능 여부 선택
      enabled: true
      # 업로드된 파일의 임시 저장 경로
      #            location: C:\
      # 한 번에 최대 업로드 가능 용량
      max-request-size: 100MB
      # 파일 하나의 최대 크기
      max-file-size: 20MB

mybatis:
  mapper-locations: mappers/**/*.xml

logging:
  level:
    org.mybatis: TRACE
    org.thymeleaf: TRACE
    org.quartz.core: TRACE
    org.hibernate.SQL: TRACE
    org.h2.server.web: TRACE
    com.mtvs.crimecapturetv: TRACE
    org.springframework.web: TRACE