server:
  port: 8080
  servlet:
    session:
      timeout: 360000s
    # 인코딩 UTF-8로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: crimecapturetv
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cctv?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cctv
    password: cctv
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #dml.sql을 실행하기위해 true설정
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:sql/dml.sql
      platform: mysql
      encoding: UTF-8
  # file upload
  servlet:
    multipart:
      # 파일 업로드 가능 여부 선택
      enabled: true
      # 업로드된 파일의 임시 저장 경로
      #            location: C:\
      # 한 번에 최대 업로드 가능 용량
      max-request-size: 100MB
      # 파일 하나의 최대 크기
      max-file-size: 20MB

  redis:
    host: 127.0.0.1
    port: 6379
    password: ${SPRING_REDIS_PASSWORD}

# Email 인증
mail:
  smtp:
    auth: true
    # MTP 서버에 인증 필요한 경우 true로 지정
    # Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정
    port: 465
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

# admin 구글 계정
AdminMail:
  id: ${MAIL_ID}
  password: ${MAIL_PASSWORD}

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: method
    display-request-duration: true

logging:
  level:
    org.mybatis: TRACE
    org.thymeleaf: TRACE
    org.quartz.core: TRACE
    org.hibernate.SQL: TRACE
    org.h2.server.web: TRACE
    com.mtvs.crimecapturetv: TRACE
    org.springframework.web: TRACE